# -*- encoding: utf-8 -*-
module ActiveMerchant
  module Shipping
    module DhlConstants

        GlobalProductCodes = {
          "0"	=> "LOGISTICS SERVICES",
          "1"	=> "CUSTOMS SERVICES",
          "2"	=> "EASY SHOP",
          "3"	=> "EASY SHOP",
          "4"	=> "JETLINE",
          "5"	=> "SPRINTLINE",
          "6"	=> "SECURELINE",
          "7"	=> "EXPRESS EASY",
          "8"	=> "EXPRESS EASY",
          "9"	=> "EUROPACK",
          "A"	=> "AUTO REVERSALS",
          "B"	=> "BREAK BULK EXPRESS",
          "C"	=> "MEDICAL EXPRESS",
          "D"	=> "EXPRESS WORLDWIDE",
          "E"	=> "EXPRESS 9:00",
          "F"	=> "FREIGHT WORLDWIDE",
          "G"	=> "DOMESTIC ECONOMY SELECT",
          "H"	=> "ECONOMY SELECT",
          "I"	=> "BREAK BULK ECONOMY",
          "J"	=> "JUMBO BOX",
          "K"	=> "EXPRESS 9:00",
          "L"	=> "EXPRESS 10:30",
          "M"	=> "EXPRESS 10:30",
          "N"	=> "DOMESTIC EXPRESS",
          "O"	=> "OTHERS",
          "P"	=> "EXPRESS WORLDWIDE",
          "Q"	=> "MEDICAL EXPRESS",
          "R"	=> "GLOBALMAIL BUSINESS",
          "S"	=> "SAME DAY",
          "T"	=> "EXPRESS 12:00",
          "U"	=> "EXPRESS WORLDWIDE",
          "V"	=> "EUROPACK",
          "W"	=> "ECONOMY SELECT",
          "X"	=> "EXPRESS ENVELOPE",
          "Y"	=> "EXPRESS 12:00",
          "Z"	=> "Destination Charges"
        }
        
        DHL_Currency_Codes = {
          "AD"	=>     "EUR",
          "AE"	=>     "AED",
          "AF"	=>     "AFN",
          "AG"	=>     "XCD",
          "AI"	=>     "XCD",
          "AL"	=>     "EUR",
          "AM"	=>     "AMD",
          "AN"	=>     "ANG",
          "AO"	=>     "AOA",
          "AR"	=>     "ARS",
          "AS"	=>     "USD",
          "AT"	=>     "EUR",
          "AU"	=>     "AUD",
          "AW"	=>     "AWG",
          "AZ"	=>     "AZM",
          "BA"	=>     "BAM",
          "BB"	=>     "BBD",
          "BD"	=>     "BDT",
          "BE"	=>     "EUR",
          "BF"	=>     "XOF",
          "BG"	=>     "BGN",
          "BH"	=>     "BHD",
          "BI"	=>     "BIF",
          "BJ"	=>     "XOF",
          "BM"	=>     "BMD",
          "BN"	=>     "BND",
          "BO"	=>     "BOB",
          "BR"	=>     "BRL",
          "BS"	=>     "BSD",
          "BT"	=>     "BTN",
          "BW"	=>     "BWP",
          "BY"	=>     "BYR",
          "BZ"	=>     "BZD",
          "CA"	=>     "CAD",
          "CD"	=>     "CDF",
          "CF"	=>     "XAF",
          "CG"	=>     "XAF",
          "CH"	=>     "CHF",
          "CI"	=>     "XOF",
          "CK"	=>     "NZD",
          "CL"	=>     "CLP",
          "CM"	=>     "XAF",
          "CN"	=>     "CNY",
          "CO"	=>     "COP",
          "CR"	=>     "CRC",
          "CU"	=>     "CUP",
          "CV"	=>     "CVE",
          "CY"	=>     "EUR",
          "CZ"	=>     "CZK",
          "DE"	=>     "EUR",
          "DJ"	=>     "DJF",
          "DK"	=>     "DKK",
          "DM"	=>     "XCD",
          "DO"	=>     "DOP",
          "DZ"	=>     "DZD",
          "EC"	=>     "USD",
          "EE"	=>     "EEK",
          "EG"	=>     "EGP",
          "ER"	=>     "ERN",
          "ES"	=>     "EUR",
          "ET"	=>     "ETB",
          "FI"	=>     "EUR",
          "FJ"	=>     "FJD",
          "FK"	=>     "FKP",
          "FM"	=>     "USD",
          "FO"	=>     "DKK",
          "FR"	=>     "EUR",
          "GA"	=>     "XAF",
          "GB"	=>     "GBP",
          "GD"	=>     "XCD",
          "GE"	=>     "GEL",
          "GF"	=>     "EUR",
          "GG"	=>     "GBP",
          "GH"	=>     "GHS",
          "GI"	=>     "GIP",
          "GL"	=>     "DKK",
          "GM"	=>     "GMD",
          "GN"	=>     "GNF",
          "GP"	=>     "EUR",
          "GQ"	=>     "XAF",
          "GR"	=>     "EUR",
          "GT"	=>     "GTQ",
          "GU"	=>     "USD",
          "GW"	=>     "GWP",
          "GY"	=>     "GYD",
          "HK"	=>     "HKD",
          "HN"	=>     "HNL",
          "HR"	=>     "HRK",
          "HT"	=>     "HTG",
          "HU"	=>     "HUF",
          "IC"	=>     "EUR",
          "ID"	=>     "IDR",
          "IE"	=>     "EUR",
          "IL"	=>     "ILS",
          "IN"	=>     "INR",
          "IQ"	=>     "IQD",
          "IR"	=>     "IRR",
          "IS"	=>     "ISK",
          "IT"	=>     "EUR",
          "JE"	=>     "GBP",
          "JM"	=>     "JMD",
          "JO"	=>     "JOD",
          "JP"	=>     "JPY",
          "KE"	=>     "KES",
          "KG"	=>     "KGS",
          "KH"	=>     "KHR",
          "KI"	=>     "AUD",
          "KM"	=>     "KMF",
          "KN"	=>     "XCD",
          "KP"	=>     "KPW",
          "KR"	=>     "KRW",
          "KV"	=>     "EUR",
          "KW"	=>     "KWD",
          "KY"	=>     "KYD",
          "KZ"	=>     "KZT",
          "LA"	=>     "LAK",
          "LB"	=>     "USD",
          "LC"	=>     "XCD",
          "LI"	=>     "CHF",
          "LK"	=>     "LKR",
          "LR"	=>     "LRD",
          "LS"	=>     "LSL",
          "LT"	=>     "LTL",
          "LU"	=>     "EUR",
          "LV"	=>     "LVL",
          "LY"	=>     "LYD",
          "MA"	=>     "MAD",
          "MC"	=>     "EUR",
          "MD"	=>     "MDL",
          "ME"	=>     "EUR",
          "MG"	=>     "MGA",
          "MH"	=>     "USD",
          "MK"	=>     "MKD",
          "ML"	=>     "XOF",
          "MM"	=>     "USD",
          "MN"	=>     "MNT",
          "MO"	=>     "MOP",
          "MP"	=>     "USD",
          "MQ"	=>     "EUR",
          "MR"	=>     "MRO",
          "MS"	=>     "XCD",
          "MT"	=>     "EUR",
          "MU"	=>     "MUR",
          "MV"	=>     "MVR",
          "MW"	=>     "MWK",
          "MX"	=>     "MXN",
          "MY"	=>     "MYR",
          "MZ"	=>     "MZN",
          "NA"	=>     "ZAR",
          "NC"	=>     "XPF",
          "NE"	=>     "XOF",
          "NG"	=>     "NGN",
          "NI"	=>     "NIO",
          "NL"	=>     "EUR",
          "NO"	=>     "NOK",
          "NP"	=>     "NPR",
          "NR"	=>     "AUD",
          "NU"	=>     "NZD",
          "NZ"	=>     "NZD",
          "OM"	=>     "OMR",
          "PA"	=>     "PAB",
          "PE"	=>     "PEN",
          "PF"	=>     "XPF",
          "PG"	=>     "PGK",
          "PH"	=>     "PHP",
          "PK"	=>     "PKR",
          "PL"	=>     "PLN",
          "PR"	=>     "USD",
          "PT"	=>     "EUR",
          "PW"	=>     "USD",
          "PY"	=>     "PYG",
          "QA"	=>     "QAR",
          "RE"	=>     "EUR",
          "RO"	=>     "RON",
          "RS"	=>     "RSD",
          "RU"	=>     "RUB",
          "RW"	=>     "RWF",
          "SA"	=>     "SAR",
          "SB"	=>     "SBD",
          "SC"	=>     "SCR",
          "SD"	=>     "SDG",
          "SE"	=>     "SEK",
          "SG"	=>     "SGD",
          "SI"	=>     "EUR",
          "SK"	=>     "EUR",
          "SL"	=>     "SLL",
          "SM"	=>     "EUR",
          "SN"	=>     "XOF",
          "SO"	=>     "SOS",
          "SR"	=>     "SRD",
          "ST"	=>     "STD",
          "SV"	=>     "USD",
          "SY"	=>     "SYP",
          "SZ"	=>     "SZL",
          "TC"	=>     "USD",
          "TD"	=>     "XAF",
          "TG"	=>     "XOF",
          "TH"	=>     "THB",
          "TJ"	=>     "TJS",
          "TL"	=>     "USD",
          "TN"	=>     "TND",
          "TO"	=>     "TOP",
          "TR"	=>     "TRY",
          "TT"	=>     "TTD",
          "TV"	=>     "AUD",
          "TW"	=>     "TWD",
          "TZ"	=>     "TZS",
          "UA"	=>     "UAH",
          "UG"	=>     "UGX",
          "US"	=>     "USD",
          "UY"	=>     "UYU",
          "UZ"	=>     "UZS",
          "VC"	=>     "XCD",
          "VE"	=>     "VEF",
          "VG"	=>     "USD",
          "VI"	=>     "USD",
          "VN"	=>     "VND",
          "VU"	=>     "VUV",
          "WS"	=>     "WST",
          "XB"	=>     "EUR",
          "XC"	=>     "EUR",
          "XE"	=>     "ANG",
          "XM"	=>     "EUR",
          "XN"	=>     "XCD",
          "XS"	=>     "SIS",
          "XY"	=>     "ANG",
          "YE"	=>     "YER",
          "YT"	=>     "EUR",
          "ZA"	=>     "ZAR",
          "ZM"	=>     "ZMK",
          "ZW"	=>     "ZWD"
        }
        
        DoorTo = {
          'DD' => "Door to Door",
          'DA' => "Door to Airport",
          'AA' => 'Door to Dor non-compliant',
          'AA' => 'Door to Dor non-compliant'
        }      
        PackageTypes = {
          "EE" => "DHL Express Envelope",
          "OD" => "Other DHL Packaging",
          "CP" => "Custom Packaging",
          "DC" => "Document",
          "DM" => "Domestic",
          "ED" => "Express Document",
          "FR" => "Freight",
          "BD" => "Jumbo Document",
          "BP" => "Jumbo Parcel",
          "JD" => "Jumbo Junior Document",
          "JP" => "Jumbo Junior Parcel",
          "PA" => "Parcel",
          "DF" => "DHL Flyer"
        }
        
        PaymentTypes = {
          'shipper' => 'S',
          'receiver' => 'R',
          'third_party' => 'T'
        }
      
        DHL_COUNTRIES = {
          AF:	"Afghanistan",
          AX:	"Åland Islands",
          AL:	"Albania",
          DZ:	"Algeria",
          AS:	"American Samoa",
          AD:	"Andorra",
          AO:	"Angola",
          AI:	"Anguilla",
          AQ:	"Antarctica",
          AG:	"Antigua and Barbuda",
          AR:	"Argentina",
          AM:	"Armenia",
          AW:	"Aruba",
          AU:	"Australia",
          AT:	"Austria",
          AZ:	"Azerbaijan",
          BS:	"Bahamas",
          BH:	"Bahrain",
          BD:	"Bangladesh",
          BB:	"Barbados",
          BY:	"Belarus",
          BE:	"Belgium",
          BZ:	"Belize",
          BJ:	"Benin",
          BM:	"Bermuda",
          BT:	"Bhutan",
          BO:	"Bolivia Plurinational State of",
          BQ:	"Bonaire Sint Eustatius and Saba",
          BA:	"Bosnia and Herzegovina",
          BW:	"Botswana",
          BV:	"Bouvet Island",
          BR:	"Brazil",
          IO:	"British Indian Ocean Territory",
          BN:	"Brunei Darussalam",
          BG:	"Bulgaria",
          BF:	"Burkina Faso",
          BI:	"Burundi",
          KH:	"Cambodia",
          CM:	"Cameroon",
          CA:	"Canada",
          CV:	"Cape Verde",
          KY:	"Cayman Islands",
          CF:	"Central African Republic",
          TD:	"Chad",
          CL:	"Chile",
          CN:	"China",
          CX:	"Christmas Island",
          CC:	"Cocos (Keeling) Islands",
          CO:	"Colombia",
          KM:	"Comoros",
          CG:	"Congo",
          CD:	"Congo the Democratic Republic of the",
          CK:	"Cook Islands",
          CR:	"Costa Rica",
          CI:	"Côte d'Ivoire",
          HR:	"Croatia",
          CU:	"Cuba",
          CW:	"Curaçao",
          CY:	"Cyprus",
          CZ:	"Czech Republic",
          DK:	"Denmark",
          DJ:	"Djibouti",
          DM:	"Dominica",
          DO:	"Dominican Republic",
          EC:	"Ecuador",
          EG:	"Egypt",
          SV:	"El Salvador",
          GQ:	"Equatorial Guinea",
          ER:	"Eritrea",
          EE:	"Estonia",
          ET:	"Ethiopia",
          FK:	"Falkland Islands (Malvinas)",
          FO:	"Faroe Islands",
          FJ:	"Fiji",
          FI:	"Finland",
          FR:	"France",
          GF:	"French Guiana",
          PF:	"French Polynesia",
          TF:	"French Southern Territories",
          GA:	"Gabon",
          GM:	"Gambia",
          GE:	"Georgia",
          DE:	"Germany",
          GH:	"Ghana",
          GI:	"Gibraltar",
          GR:	"Greece",
          GL:	"Greenland",
          GD:	"Grenada",
          GP:	"Guadeloupe",
          GU:	"Guam",
          GT:	"Guatemala",
          GG:	"Guernsey",
          GN:	"Guinea",
          GW:	"Guinea-Bissau",
          GY:	"Guyana",
          HT:	"Haiti",
          HM:	"Heard Island and McDonald Islands",
          VA:	"Holy See (Vatican City State)",
          HN:	"Honduras",
          HK:	"Hong Kong",
          HU:	"Hungary",
          IS:	"Iceland",
          IN:	"India",
          ID:	"Indonesia",
          IR:	"Iran Islamic Republic of",
          IQ:	"Iraq",
          IE:	"Ireland",
          IM:	"Isle of Man",
          IL:	"Israel",
          IT:	"Italy",
          JM:	"Jamaica",
          JP:	"Japan",
          JE:	"Jersey",
          JO:	"Jordan",
          KZ:	"Kazakhstan",
          KE:	"Kenya",
          KI:	"Kiribati",
          KP:	"Korea Democratic People's Republic of",
          KR:	"Korea Republic of",
          KW:	"Kuwait",
          KG:	"Kyrgyzstan",
          LA:	"Lao People's Democratic Republic",
          LV:	"Latvia",
          LB:	"Lebanon",
          LS:	"Lesotho",
          LR:	"Liberia",
          LY:	"Libya",
          LI:	"Liechtenstein",
          LT:	"Lithuania",
          LU:	"Luxembourg",
          MO:	"Macao",
          MK:	"Macedonia The Former Yugoslav Republic of",
          MG:	"Madagascar",
          MW:	"Malawi",
          MY:	"Malaysia",
          MV:	"Maldives",
          ML:	"Mali",
          MT:	"Malta",
          MH:	"Marshall Islands",
          MQ:	"Martinique",
          MR:	"Mauritania",
          MU:	"Mauritius",
          YT:	"Mayotte",
          MX:	"Mexico",
          FM:	"Micronesia Federated States of",
          MD:	"Moldova Republic of",
          MC:	"Monaco",
          MN:	"Mongolia",
          ME:	"Montenegro",
          MS:	"Montserrat",
          MA:	"Morocco",
          MZ:	"Mozambique",
          MM:	"Myanmar",
          NA:	"Namibia",
          NR:	"Nauru",
          NP:	"Nepal",
          NL:	"Netherlands",
          NC:	"New Caledonia",
          NZ:	"New Zealand",
          NI:	"Nicaragua",
          NE:	"Niger",
          NG:	"Nigeria",
          NU:	"Niue",
          NF:	"Norfolk Island",
          MP:	"Northern Mariana Islands",
          NO:	"Norway",
          OM:	"Oman",
          PK:	"Pakistan",
          PW:	"Palau",
          PS:	"Palestine State of",
          PA:	"Panama",
          PG:	"Papua New Guinea",
          PY:	"Paraguay",
          PE:	"Peru",
          PH:	"Philippines",
          PN:	"Pitcairn",
          PL:	"Poland",
          PT:	"Portugal",
          PR:	"Puerto Rico",
          QA:	"Qatar",
          RE:	"Réunion",
          RO:	"Romania",
          RU:	"Russian Federation",
          RW:	"Rwanda",
          BL:	"Saint Barthélemy",
          SH:	"Saint Helena Ascension and Tristan da Cunha",
          KN:	"Saint Kitts and Nevis",
          LC:	"Saint Lucia",
          MF:	"Saint Martin (French part)",
          PM:	"Saint Pierre and Miquelon",
          VC:	"Saint Vincent and the Grenadines",
          WS:	"Samoa",
          SM:	"San Marino",
          ST:	"Sao Tome and Principe",
          SA:	"Saudi Arabia",
          SN:	"Senegal",
          RS:	"Serbia",
          SC:	"Seychelles",
          SL:	"Sierra Leone",
          SG:	"Singapore",
          SX:	"Sint Maarten (Dutch part)",
          SK:	"Slovakia",
          SI:	"Slovenia",
          SB:	"Solomon Islands",
          SO:	"Somalia",
          ZA:	"South Africa",
          GS:	"South Georgia and the South Sandwich Islands",
          SS:	"South Sudan",
          ES:	"Spain",
          LK:	"Sri Lanka",
          SD:	"Sudan",
          SR:	"Suriname",
          SJ:	"Svalbard and Jan Mayen",
          SZ:	"Swaziland",
          SE:	"Sweden",
          CH:	"Switzerland",
          SY:	"Syrian Arab Republic",
          TW:	"Taiwan Province of China",
          TJ:	"Tajikistan",
          TZ:	"Tanzania United Republic of",
          TH:	"Thailand",
          TL:	"Timor-Leste",
          TG:	"Togo",
          TK:	"Tokelau",
          TO:	"Tonga",
          TT:	"Trinidad and Tobago",
          TN:	"Tunisia",
          TR:	"Turkey",
          TM:	"Turkmenistan",
          TC:	"Turks and Caicos Islands",
          TV:	"Tuvalu",
          UG:	"Uganda",
          UA:	"Ukraine",
          AE:	"United Arab Emirates",
          GB:	"United Kingdom",
          US:	"United States",
          UM:	"United States Minor Outlying Islands",
          UY:	"Uruguay",
          UZ:	"Uzbekistan",
          VU:	"Vanuatu",
          VE:	"Venezuela Bolivarian Republic of",
          VN:	"Viet Nam",
          VG:	"Virgin Islands British",
          VI:	"Virgin Islands U.S.",
          WF:	"Wallis and Futuna",
          EH:	"Western Sahara",
          YE:	"Yemen",
          ZM:	"Zambia",
          ZW:	"Zimbabwe"
        }      
    end
  end
end